### ISSUE TITLE
Investigate how to change SimpleOrderService to adhere SOLID principles

### ISSUE THREAD

**Issue by taras-oglabyak** [Andrii77711/order-management-service#7]
1. Learn about SOLID.
2. Identify what should not be placed in `SimpleOrderService` and add details in comments of this GH Issue.
3. Log a new GH Issue to apply needed refactoring.

**Comment by Andrii77711** [comment]
Single Responsibility Principle (SRP) – Principle detection is flawed: Violation: The SimpleOrderService class performs multiple tasks: order retrieval, total price calculation, and entity conversion. Solution: Split responsibilities into service-specific classes.

Open/Closed Principle (OCP) – Open/Closed Principle: Violation: The SimpleOrderService class will be difficult to extend without modifying its code. Solution: Use interfaces and abstractions for different operations.

Liskov Substitution Principle (LSP) – Liskov Substitution Principle: Not violated.

Interface Segregation Principle (ISP) – Interface Segregation Principle: Violation: The OrderService interface may be too broad. Solution: Split interfaces into narrower and more specialized ones.

Dependency Inversion Principle (DIP) – Dependency Inversion Principle: Violation: Direct dependencies on specific repositories. Solution: Use abstractions for dependencies.

Necessary changes: Create interfaces for each operation: OrderService, OrderItemService, ProductService. Split the SimpleOrderService class into several services: OrderServiceImpl, OrderItemServiceImpl, ProductServiceImpl. Create converter classes for transformations: Order to OrderDetails, OrderItem to OrderItemDetails, Product to ProductDetails. This will help adhere to the Single Responsibility Principle (SRP) and improve the architecture of the code.
